{
  "Uuid": "d320885f-7fb4-4ea4-aa11-a14a020bbb64",
  "IsCustomNode": false,
  "Description": null,
  "Name": "Geometry01",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "a94b68e3a3c34bd590386da8efca4250",
      "Inputs": [
        {
          "Id": "8fe1008cd427469b81e5bbcd64a10d11",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8d6da171ceee497aa0bbcaec48893de1",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "01d5a5265b5c4a968e835e46a31aa0d9",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2c9a1f46b14340eabdf39812547fccc9",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "5e04a8ab6b174831910d436648be8360",
      "Inputs": [
        {
          "Id": "1c34754dac664fcc888afefbb0b5bc8f",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7ac42c83b5a345879e2c3275e7ad0341",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4165a525551144c1a81db3faf36931ed",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "34086999707c4725b466221b7b330648",
      "Inputs": [
        {
          "Id": "853d975f9131408aaf22825a40f08543",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "907fbda15c574fe8891a7f34567dfce0",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d6cc5ad0c66c4f0da7b14e11e6280040",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "d83d83a9d71147b7b8cb3032606af1fe",
      "Inputs": [
        {
          "Id": "dedc680233e14c84b3a71a12de6b2018",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3938d3e8bedf422399b9cf85b5e49cc0",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "605857d397464d2580e80396264e76f9",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "10;",
      "Id": "45ec5c90712343ee88fce8d088391a40",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d1408124d22c4dac83d945c91a1bac6c",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "15;",
      "Id": "2fb3486387634dc5b185dfa94a83a6e9",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "cb0569c4649e407b840e9262537980d8",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "8;",
      "Id": "6d3e772713364b5a98dc7c121b2149a2",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8a9cd17d99c84ca2bc03d654d2d8e97f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "c40dee4e31374af4b5314ee49aa05829",
      "Inputs": [
        {
          "Id": "d86965b43c514f16bd0c4767c4ce41a1",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ec74a679de114657b9e653955b8178b0",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c90af00b7cc44e47a80fb96caf426a1b",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6d8028f9650f4dff915fc0d8043877fb",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "ae3f4584620348eaaa15ff5910a87489",
      "Inputs": [
        {
          "Id": "d1ad6156e65c48adbb552d48b1150813",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "26594bbc50b24c7a93691a849574d2f2",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid by lofting between input cross section closed Curves.\n\nSolid.ByLoft (crossSections: Curve[]): Solid"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "9dd3ad9e9a5e4a75afd5afe91601cb7e",
      "Inputs": [
        {
          "Id": "19db280fe5b54e1ba7775c92829cefb9",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bba696d7236743898ed53cf840944250",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d32bf010e33843dfb9759dfd63a1db7a",
          "Name": "item2",
          "Description": "Item Index #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "02176fa05b464353bcaaf7e28f35b8c3",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "7;",
      "Id": "d5e72f36a2844f5688c7da58d8c4f242",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2cdd40a3303c42a18db73c2772e82e89",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.Fillet@Autodesk.DesignScript.Geometry.Edge[],double",
      "Id": "ff829b223ea141ea9cb025058c8f68f6",
      "Inputs": [
        {
          "Id": "936a26fc0bac4aa1b5113e6270124b4b",
          "Name": "solid",
          "Description": "Autodesk.DesignScript.Geometry.Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "283d0e3c2fbb487f8cd7fcd30feadbd2",
          "Name": "edges",
          "Description": "Edge[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ea3d200ebb2a4f5ab17b4941ac19cc4a",
          "Name": "radius",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "477e445629d04985a84fadfa43d214f3",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Fillets a Solid along input Edges with a given radius.\n\nSolid.Fillet (edges: Edge[], radius: double): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Face.Edges",
      "Id": "37b067d00151497e89b011598bc15e76",
      "Inputs": [
        {
          "Id": "5716cba54967484fada143e07989aba8",
          "Name": "face",
          "Description": "Autodesk.DesignScript.Geometry.Face",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "138822e2befa476cb62293b15c857e74",
          "Name": "Edge[]",
          "Description": "Edge[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "All of the Edges around this Face in counterclockwise order\n\nFace.Edges: Edge[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Edges",
      "Id": "984528d4c9d041b3a5ca99b93b0f3181",
      "Inputs": [
        {
          "Id": "b1bd46153a3c444e99da41ee4414b040",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f08b4de8a9f4409a9e70f42573f32c33",
          "Name": "Edge[]",
          "Description": "Edge[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Edges of the Topology\n\nTopology.Edges: Edge[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Faces",
      "Id": "0476dd5a29554a9995dc63d30efc7520",
      "Inputs": [
        {
          "Id": "b6f3ffd450d04de78394ca3050b94c2b",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4310d74f0362403da7d48adf02a40377",
          "Name": "Face[]",
          "Description": "Face[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Faces of the Topology\n\nTopology.Faces: Face[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "2;",
      "Id": "dc4125f00f694a118cd0ad115e39758e",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d45e1cb7f8bc4a5f922da482569e023a",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 10.0,
      "MinimumValue": 1.0,
      "StepValue": 0.1,
      "InputValue": 2.6,
      "Id": "b965fb85eacd405991eac576e49b059a",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e3c26860491541579b119bc13d2e4243",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 10.0,
      "MinimumValue": 1.0,
      "StepValue": 0.1,
      "InputValue": 2.0,
      "Id": "1b852cbea5904630a69fa9311bbf76ec",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a4c182b556764247925124b6e1a5ec56",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.BySweep@Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Curve",
      "Id": "367dae2443af4098a92d840580063e98",
      "Inputs": [
        {
          "Id": "b182701189af46768a184fc3bd83e25e",
          "Name": "profile",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f48a44cb19aa4f7883eeeb71dd982c12",
          "Name": "path",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2807803c8b004161ae08f635ed9abd3e",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Sweep a closed Curve along a path.\n\nSolid.BySweep (profile: Curve, path: Curve): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByRevolve@Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,double,double",
      "Id": "69601fc697cb4186a5d29840054d1005",
      "Inputs": [
        {
          "Id": "2f52af4130e847bba3d7e62f93232693",
          "Name": "profile",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6f724b3681db489ca4e22bc6ed1ff67c",
          "Name": "axisOrigin",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0a8f0c3b3ae34bb2a83dcf59ca21f8eb",
          "Name": "axisDirection",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b8eeb45fed63499a89ea8aaa995900af",
          "Name": "startAngle",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b12f52d1544640be9499a6207f4ae4e2",
          "Name": "sweepAngle",
          "Description": "double\nDefault value : 180",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6adc93d71b564b67a626b114736009b7",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid of revolution, sweeping the profile Curve around the axis Ray formed by the origin and the axis Vector, from the start angle in degrees to the sweep angle in degrees.\n\nSolid.ByRevolve (profile: Curve, axisOrigin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), axisDirection: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1), startAngle: double = 0, sweepAngle: double = 180): Solid"
    }
  ],
  "Connectors": [
    {
      "Start": "2c9a1f46b14340eabdf39812547fccc9",
      "End": "853d975f9131408aaf22825a40f08543",
      "Id": "6999a3e133884cb08239b308aa36072f"
    },
    {
      "Start": "4165a525551144c1a81db3faf36931ed",
      "End": "19db280fe5b54e1ba7775c92829cefb9",
      "Id": "e42363973c42418ab6f6a7c83b2a0a15"
    },
    {
      "Start": "d6cc5ad0c66c4f0da7b14e11e6280040",
      "End": "bba696d7236743898ed53cf840944250",
      "Id": "6fdca0b419904b4691c943d09ee9f5e2"
    },
    {
      "Start": "605857d397464d2580e80396264e76f9",
      "End": "d32bf010e33843dfb9759dfd63a1db7a",
      "Id": "16ac26246d00485f9151a6b33cb66f2e"
    },
    {
      "Start": "d1408124d22c4dac83d945c91a1bac6c",
      "End": "7ac42c83b5a345879e2c3275e7ad0341",
      "Id": "66eb51e4ba64448f8f0a07afd8f384cb"
    },
    {
      "Start": "d1408124d22c4dac83d945c91a1bac6c",
      "End": "01d5a5265b5c4a968e835e46a31aa0d9",
      "Id": "3dddb8df5d734b3cb8415c4a35f5b8d2"
    },
    {
      "Start": "cb0569c4649e407b840e9262537980d8",
      "End": "c90af00b7cc44e47a80fb96caf426a1b",
      "Id": "4c8f3b504db94003ae2fc87adf11fb9d"
    },
    {
      "Start": "8a9cd17d99c84ca2bc03d654d2d8e97f",
      "End": "3938d3e8bedf422399b9cf85b5e49cc0",
      "Id": "4b8dde3a20274888a4d2f2e76ed62549"
    },
    {
      "Start": "6d8028f9650f4dff915fc0d8043877fb",
      "End": "dedc680233e14c84b3a71a12de6b2018",
      "Id": "0565928f40154e70940e9c8e99c3f3b9"
    },
    {
      "Start": "26594bbc50b24c7a93691a849574d2f2",
      "End": "936a26fc0bac4aa1b5113e6270124b4b",
      "Id": "9d2b4082ca784c2a9eb7322feaef235d"
    },
    {
      "Start": "26594bbc50b24c7a93691a849574d2f2",
      "End": "b1bd46153a3c444e99da41ee4414b040",
      "Id": "eaa6ab87887b4320bc85f9f2667a61c0"
    },
    {
      "Start": "02176fa05b464353bcaaf7e28f35b8c3",
      "End": "d1ad6156e65c48adbb552d48b1150813",
      "Id": "e212b26761134a07bc72d1556c0e06de"
    },
    {
      "Start": "f08b4de8a9f4409a9e70f42573f32c33",
      "End": "283d0e3c2fbb487f8cd7fcd30feadbd2",
      "Id": "c95c59dc857942c7bc9b3de7722999b7"
    },
    {
      "Start": "e3c26860491541579b119bc13d2e4243",
      "End": "ea3d200ebb2a4f5ab17b4941ac19cc4a",
      "Id": "9f93fdca019c47dba94e4866f10e2561"
    },
    {
      "Start": "a4c182b556764247925124b6e1a5ec56",
      "End": "907fbda15c574fe8891a7f34567dfce0",
      "Id": "0986e727053941d3a6c1cc13941f8c2a"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.3.0.5885",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -54.674354346847352,
      "EyeY": 22.250017648149896,
      "EyeZ": 43.187058143008038,
      "LookX": 27.677700625527528,
      "LookY": -23.558109432451946,
      "LookZ": -52.742025954074087,
      "UpX": 0.074293232039893992,
      "UpY": 0.98713626507297669,
      "UpZ": -0.14157157147823865
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "a94b68e3a3c34bd590386da8efca4250",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 10.04176451866141,
        "Y": 87.7386412866349
      },
      {
        "ShowGeometry": true,
        "Name": "Circle.ByCenterPointRadius",
        "Id": "5e04a8ab6b174831910d436648be8360",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 492.86652935180962,
        "Y": -43.710485436351036
      },
      {
        "ShowGeometry": true,
        "Name": "Circle.ByCenterPointRadius",
        "Id": "34086999707c4725b466221b7b330648",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 503.40342078606659,
        "Y": 139.74411755176732
      },
      {
        "ShowGeometry": true,
        "Name": "Circle.ByCenterPointRadius",
        "Id": "d83d83a9d71147b7b8cb3032606af1fe",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 502.52317500690708,
        "Y": 298.667618034574
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "45ec5c90712343ee88fce8d088391a40",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -103.56786904785497,
        "Y": -46.281162328553819
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "2fb3486387634dc5b185dfa94a83a6e9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -6.1719482870531692,
        "Y": 275.41007699976171
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "6d3e772713364b5a98dc7c121b2149a2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 147.0,
        "Y": 434.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "c40dee4e31374af4b5314ee49aa05829",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 227.33071270746137,
        "Y": 308.53496579636351
      },
      {
        "ShowGeometry": false,
        "Name": "Solid.ByLoft",
        "Id": "ae3f4584620348eaaa15ff5910a87489",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1014.4507398982271,
        "Y": 63.546384079893073
      },
      {
        "ShowGeometry": true,
        "Name": "List Create",
        "Id": "9dd3ad9e9a5e4a75afd5afe91601cb7e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 867.54467040552515,
        "Y": 92.808876345885238
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "d5e72f36a2844f5688c7da58d8c4f242",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 269.04248728538505,
        "Y": 161.965410428038
      },
      {
        "ShowGeometry": true,
        "Name": "Solid.Fillet",
        "Id": "ff829b223ea141ea9cb025058c8f68f6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1574.9008753259977,
        "Y": -35.867798551646956
      },
      {
        "ShowGeometry": true,
        "Name": "Face.Edges",
        "Id": "37b067d00151497e89b011598bc15e76",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1271.9063153905952,
        "Y": -208.21332805618789
      },
      {
        "ShowGeometry": true,
        "Name": "Topology.Edges",
        "Id": "984528d4c9d041b3a5ca99b93b0f3181",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1295.5343315323469,
        "Y": -3.9004825951595592
      },
      {
        "ShowGeometry": true,
        "Name": "Topology.Faces",
        "Id": "0476dd5a29554a9995dc63d30efc7520",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 884.82381565660626,
        "Y": -183.1954286119803
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "dc4125f00f694a118cd0ad115e39758e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1356.6101166975441,
        "Y": 96.0
      },
      {
        "ShowGeometry": true,
        "Name": "Number Slider",
        "Id": "b965fb85eacd405991eac576e49b059a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1151.3980566726088,
        "Y": 184.7403768248239
      },
      {
        "ShowGeometry": true,
        "Name": "Number Slider",
        "Id": "1b852cbea5904630a69fa9311bbf76ec",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -332.92165520697495,
        "Y": 249.96494623268745
      },
      {
        "ShowGeometry": true,
        "Name": "Solid.BySweep",
        "Id": "367dae2443af4098a92d840580063e98",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1537.7980935836229,
        "Y": 278.58269435248286
      },
      {
        "ShowGeometry": true,
        "Name": "Solid.ByRevolve",
        "Id": "69601fc697cb4186a5d29840054d1005",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1946.3167379501224,
        "Y": 164.60373556514458
      }
    ],
    "Annotations": [],
    "X": -396.39447222998047,
    "Y": 300.26681666379676,
    "Zoom": 0.7089027734562523
  }
}